server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    sentinel:
      transport:
        dashboard: 172.20.10.12:8080 # 指定控制台服务的地址
        port: 8720
      enabled: true
      eager: true
      filter:
        enabled: false
    nacos:
      discovery:
        server-addr: 172.20.10.12:8848
        group: DEFAULT_GROUP
        namespace: 66dcef34-3556-4a8d-a1c7-71c95f7b042d
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowedOriginPatterns: '*'
            allowedMethods: '*'
            allowedHeaders: '*'
            maxAge: 360000
            exposedHeaders: '*'
      #      discovery:
      #        locator:
      #          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      #          lowerCaseServiceId: true
      #          filters:
      #            - StripPrefix=0
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9000 #匹配后提供服务的路由地址
          predicates:
            - Path=/test/**         # 断言，路径相匹配的进行路由
        - id: test-service
          uri: lb://test-service
          predicates:
            - Path=/test-service/**