# Tomcat
server:
  port: 9000
# Spring
spring:
  config:
    import:
      - optional:nacos:test-service.yaml
  application:
    # 应用名称
    name: test-service
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 172.20.10.12:8848
        group: DEFAULT_GROUP
        namespace: 66dcef34-3556-4a8d-a1c7-71c95f7b042d
        register-enabled: true
      config:
        server-addr: 172.20.10.12:8848 #Nacos作为配置中心地址
        group: DEFAULT_GROUP
        namespace: 66dcef34-3556-4a8d-a1c7-71c95f7b042d
        file-extension: yaml #指定yaml格式的配置
    sentinel:
      transport:
        dashboard: 172.20.10.12:8080 # 指定控制台服务的地址
        port: 8719
      filter:
        url-patterns: /**
      enabled: true
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.nacos.client: info
